/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ShadowHubRouteImport } from './routes/shadow-hub'
import { Route as RenovarServidorRouteImport } from './routes/renovar-servidor'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrimeirosPassosRouteImport } from './routes/primeiros-passos'
import { Route as PresentesRouteImport } from './routes/presentes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MigracaoRouteImport } from './routes/migracao'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorialIdRouteImport } from './routes/tutorial.$id'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento.pendente'
import { Route as PagamentoErroRouteImport } from './routes/pagamento.erro'
import { Route as PagamentoCheckoutRouteImport } from './routes/pagamento.checkout'
import { Route as AuthenticatedTutoriaisRouteImport } from './routes/_authenticated/tutoriais'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedSugestoesRouteImport } from './routes/_authenticated/sugestoes'
import { Route as AuthenticatedStaffChatRouteImport } from './routes/_authenticated/staff-chat'
import { Route as AuthenticatedStaffAcademyRouteImport } from './routes/_authenticated/staff-academy'
import { Route as AuthenticatedShadowPassRouteImport } from './routes/_authenticated/shadow-pass'
import { Route as AuthenticatedPlayProtectRouteImport } from './routes/_authenticated/play-protect'
import { Route as AuthenticatedFidelidadeRouteImport } from './routes/_authenticated/fidelidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiApkBuilderIndexRouteImport } from './routes/api/apk-builder/index'
import { Route as ApiPublicTutorialsRouteImport } from './routes/api/public/tutorials'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicBackendHealthRouteImport } from './routes/api/public/backend-health'
import { Route as ApiChatLicenseAiRouteImport } from './routes/api/chat/license-ai'
import { Route as AuthenticatedServidorStatusRouteImport } from './routes/_authenticated/servidor/status'
import { Route as AuthenticatedServidorKrakenRouteImport } from './routes/_authenticated/servidor/kraken'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsMercadopagoRouteImport } from './routes/api/public/payments/mercadopago'
import { Route as ApiPublicHooksVerifyExternalPayersRouteImport } from './routes/api/public/hooks/verify-external-payers'
import { Route as ApiPublicHooksResendConfirmationsRouteImport } from './routes/api/public/hooks/resend-confirmations'
import { Route as ApiPublicHooksReconcilePendingRouteImport } from './routes/api/public/hooks/reconcile-pending'
import { Route as ApiPublicHooksMigrationWaveEnforceRouteImport } from './routes/api/public/hooks/migration-wave-enforce'
import { Route as ApiPublicHooksExpireLicensesRouteImport } from './routes/api/public/hooks/expire-licenses'
import { Route as ApiPublicHooksDailyMaintenanceRouteImport } from './routes/api/public/hooks/daily-maintenance'
import { Route as ApiPublicHooksDailyLicenseCheckRouteImport } from './routes/api/public/hooks/daily-license-check'
import { Route as ApiPublicHooksCryptoPollRouteImport } from './routes/api/public/hooks/crypto-poll'
import { Route as ApiPublicHooksCleanupApkJobsRouteImport } from './routes/api/public/hooks/cleanup-apk-jobs'
import { Route as ApiPublicHooksAutoCloseTicketsRouteImport } from './routes/api/public/hooks/auto-close-tickets'
import { Route as ApiPublicHooksApkWorkerRouteImport } from './routes/api/public/hooks/apk-worker'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowHubRoute = ShadowHubRouteImport.update({
  id: '/shadow-hub',
  path: '/shadow-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovarServidorRoute = RenovarServidorRouteImport.update({
  id: '/renovar-servidor',
  path: '/renovar-servidor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeirosPassosRoute = PrimeirosPassosRouteImport.update({
  id: '/primeiros-passos',
  path: '/primeiros-passos',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentesRoute = PresentesRouteImport.update({
  id: '/presentes',
  path: '/presentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MigracaoRoute = MigracaoRouteImport.update({
  id: '/migracao',
  path: '/migracao',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialIdRoute = TutorialIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TutorialRoute,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pagamento/pendente',
  path: '/pagamento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoErroRoute = PagamentoErroRouteImport.update({
  id: '/pagamento/erro',
  path: '/pagamento/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoCheckoutRoute = PagamentoCheckoutRouteImport.update({
  id: '/pagamento/checkout',
  path: '/pagamento/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutoriaisRoute = AuthenticatedTutoriaisRouteImport.update({
  id: '/tutoriais',
  path: '/tutoriais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugestoesRoute = AuthenticatedSugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffChatRoute = AuthenticatedStaffChatRouteImport.update({
  id: '/staff-chat',
  path: '/staff-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffAcademyRoute =
  AuthenticatedStaffAcademyRouteImport.update({
    id: '/staff-academy',
    path: '/staff-academy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShadowPassRoute = AuthenticatedShadowPassRouteImport.update({
  id: '/shadow-pass',
  path: '/shadow-pass',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayProtectRoute =
  AuthenticatedPlayProtectRouteImport.update({
    id: '/play-protect',
    path: '/play-protect',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFidelidadeRoute = AuthenticatedFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiApkBuilderIndexRoute = ApiApkBuilderIndexRouteImport.update({
  id: '/api/apk-builder/',
  path: '/api/apk-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTutorialsRoute = ApiPublicTutorialsRouteImport.update({
  id: '/api/public/tutorials',
  path: '/api/public/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackendHealthRoute = ApiPublicBackendHealthRouteImport.update({
  id: '/api/public/backend-health',
  path: '/api/public/backend-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatLicenseAiRoute = ApiChatLicenseAiRouteImport.update({
  id: '/api/chat/license-ai',
  path: '/api/chat/license-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServidorStatusRoute =
  AuthenticatedServidorStatusRouteImport.update({
    id: '/servidor/status',
    path: '/servidor/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServidorKrakenRoute =
  AuthenticatedServidorKrakenRouteImport.update({
    id: '/servidor/kraken',
    path: '/servidor/kraken',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMercadopagoRoute =
  ApiPublicPaymentsMercadopagoRouteImport.update({
    id: '/api/public/payments/mercadopago',
    path: '/api/public/payments/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerifyExternalPayersRoute =
  ApiPublicHooksVerifyExternalPayersRouteImport.update({
    id: '/api/public/hooks/verify-external-payers',
    path: '/api/public/hooks/verify-external-payers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendConfirmationsRoute =
  ApiPublicHooksResendConfirmationsRouteImport.update({
    id: '/api/public/hooks/resend-confirmations',
    path: '/api/public/hooks/resend-confirmations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcilePendingRoute =
  ApiPublicHooksReconcilePendingRouteImport.update({
    id: '/api/public/hooks/reconcile-pending',
    path: '/api/public/hooks/reconcile-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMigrationWaveEnforceRoute =
  ApiPublicHooksMigrationWaveEnforceRouteImport.update({
    id: '/api/public/hooks/migration-wave-enforce',
    path: '/api/public/hooks/migration-wave-enforce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExpireLicensesRoute =
  ApiPublicHooksExpireLicensesRouteImport.update({
    id: '/api/public/hooks/expire-licenses',
    path: '/api/public/hooks/expire-licenses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyMaintenanceRoute =
  ApiPublicHooksDailyMaintenanceRouteImport.update({
    id: '/api/public/hooks/daily-maintenance',
    path: '/api/public/hooks/daily-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyLicenseCheckRoute =
  ApiPublicHooksDailyLicenseCheckRouteImport.update({
    id: '/api/public/hooks/daily-license-check',
    path: '/api/public/hooks/daily-license-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCryptoPollRoute =
  ApiPublicHooksCryptoPollRouteImport.update({
    id: '/api/public/hooks/crypto-poll',
    path: '/api/public/hooks/crypto-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupApkJobsRoute =
  ApiPublicHooksCleanupApkJobsRouteImport.update({
    id: '/api/public/hooks/cleanup-apk-jobs',
    path: '/api/public/hooks/cleanup-apk-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCloseTicketsRoute =
  ApiPublicHooksAutoCloseTicketsRouteImport.update({
    id: '/api/public/hooks/auto-close-tickets',
    path: '/api/public/hooks/auto-close-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApkWorkerRoute = ApiPublicHooksApkWorkerRouteImport.update({
  id: '/api/public/hooks/apk-worker',
  path: '/api/public/hooks/apk-worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/crypto': typeof CryptoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mercado': typeof MercadoRoute
  '/migracao': typeof MigracaoRoute
  '/planos': typeof PlanosRoute
  '/presentes': typeof PresentesRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/renovar-servidor': typeof RenovarServidorRoute
  '/shadow-hub': typeof ShadowHubRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/play-protect': typeof AuthenticatedPlayProtectRoute
  '/shadow-pass': typeof AuthenticatedShadowPassRoute
  '/staff-academy': typeof AuthenticatedStaffAcademyRoute
  '/staff-chat': typeof AuthenticatedStaffChatRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/pagamento/checkout': typeof PagamentoCheckoutRoute
  '/pagamento/erro': typeof PagamentoErroRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/tutorial/$id': typeof TutorialIdRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/servidor/kraken': typeof AuthenticatedServidorKrakenRoute
  '/servidor/status': typeof AuthenticatedServidorStatusRoute
  '/api/chat/license-ai': typeof ApiChatLicenseAiRoute
  '/api/public/backend-health': typeof ApiPublicBackendHealthRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/apk-builder/': typeof ApiApkBuilderIndexRoute
  '/api/public/hooks/apk-worker': typeof ApiPublicHooksApkWorkerRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/hooks/cleanup-apk-jobs': typeof ApiPublicHooksCleanupApkJobsRoute
  '/api/public/hooks/crypto-poll': typeof ApiPublicHooksCryptoPollRoute
  '/api/public/hooks/daily-license-check': typeof ApiPublicHooksDailyLicenseCheckRoute
  '/api/public/hooks/daily-maintenance': typeof ApiPublicHooksDailyMaintenanceRoute
  '/api/public/hooks/expire-licenses': typeof ApiPublicHooksExpireLicensesRoute
  '/api/public/hooks/migration-wave-enforce': typeof ApiPublicHooksMigrationWaveEnforceRoute
  '/api/public/hooks/reconcile-pending': typeof ApiPublicHooksReconcilePendingRoute
  '/api/public/hooks/resend-confirmations': typeof ApiPublicHooksResendConfirmationsRoute
  '/api/public/hooks/verify-external-payers': typeof ApiPublicHooksVerifyExternalPayersRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/crypto': typeof CryptoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mercado': typeof MercadoRoute
  '/migracao': typeof MigracaoRoute
  '/planos': typeof PlanosRoute
  '/presentes': typeof PresentesRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/renovar-servidor': typeof RenovarServidorRoute
  '/shadow-hub': typeof ShadowHubRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/play-protect': typeof AuthenticatedPlayProtectRoute
  '/shadow-pass': typeof AuthenticatedShadowPassRoute
  '/staff-academy': typeof AuthenticatedStaffAcademyRoute
  '/staff-chat': typeof AuthenticatedStaffChatRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/pagamento/checkout': typeof PagamentoCheckoutRoute
  '/pagamento/erro': typeof PagamentoErroRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/tutorial/$id': typeof TutorialIdRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/servidor/kraken': typeof AuthenticatedServidorKrakenRoute
  '/servidor/status': typeof AuthenticatedServidorStatusRoute
  '/api/chat/license-ai': typeof ApiChatLicenseAiRoute
  '/api/public/backend-health': typeof ApiPublicBackendHealthRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/apk-builder': typeof ApiApkBuilderIndexRoute
  '/api/public/hooks/apk-worker': typeof ApiPublicHooksApkWorkerRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/hooks/cleanup-apk-jobs': typeof ApiPublicHooksCleanupApkJobsRoute
  '/api/public/hooks/crypto-poll': typeof ApiPublicHooksCryptoPollRoute
  '/api/public/hooks/daily-license-check': typeof ApiPublicHooksDailyLicenseCheckRoute
  '/api/public/hooks/daily-maintenance': typeof ApiPublicHooksDailyMaintenanceRoute
  '/api/public/hooks/expire-licenses': typeof ApiPublicHooksExpireLicensesRoute
  '/api/public/hooks/migration-wave-enforce': typeof ApiPublicHooksMigrationWaveEnforceRoute
  '/api/public/hooks/reconcile-pending': typeof ApiPublicHooksReconcilePendingRoute
  '/api/public/hooks/resend-confirmations': typeof ApiPublicHooksResendConfirmationsRoute
  '/api/public/hooks/verify-external-payers': typeof ApiPublicHooksVerifyExternalPayersRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/crypto': typeof CryptoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/mercado': typeof MercadoRoute
  '/migracao': typeof MigracaoRoute
  '/planos': typeof PlanosRoute
  '/presentes': typeof PresentesRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar': typeof RecuperarRoute
  '/renovar-servidor': typeof RenovarServidorRoute
  '/shadow-hub': typeof ShadowHubRoute
  '/termos': typeof TermosRoute
  '/tutorial': typeof TutorialRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fidelidade': typeof AuthenticatedFidelidadeRoute
  '/_authenticated/play-protect': typeof AuthenticatedPlayProtectRoute
  '/_authenticated/shadow-pass': typeof AuthenticatedShadowPassRoute
  '/_authenticated/staff-academy': typeof AuthenticatedStaffAcademyRoute
  '/_authenticated/staff-chat': typeof AuthenticatedStaffChatRoute
  '/_authenticated/sugestoes': typeof AuthenticatedSugestoesRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/tutoriais': typeof AuthenticatedTutoriaisRoute
  '/pagamento/checkout': typeof PagamentoCheckoutRoute
  '/pagamento/erro': typeof PagamentoErroRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/tutorial/$id': typeof TutorialIdRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/servidor/kraken': typeof AuthenticatedServidorKrakenRoute
  '/_authenticated/servidor/status': typeof AuthenticatedServidorStatusRoute
  '/api/chat/license-ai': typeof ApiChatLicenseAiRoute
  '/api/public/backend-health': typeof ApiPublicBackendHealthRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tutorials': typeof ApiPublicTutorialsRoute
  '/api/apk-builder/': typeof ApiApkBuilderIndexRoute
  '/api/public/hooks/apk-worker': typeof ApiPublicHooksApkWorkerRoute
  '/api/public/hooks/auto-close-tickets': typeof ApiPublicHooksAutoCloseTicketsRoute
  '/api/public/hooks/cleanup-apk-jobs': typeof ApiPublicHooksCleanupApkJobsRoute
  '/api/public/hooks/crypto-poll': typeof ApiPublicHooksCryptoPollRoute
  '/api/public/hooks/daily-license-check': typeof ApiPublicHooksDailyLicenseCheckRoute
  '/api/public/hooks/daily-maintenance': typeof ApiPublicHooksDailyMaintenanceRoute
  '/api/public/hooks/expire-licenses': typeof ApiPublicHooksExpireLicensesRoute
  '/api/public/hooks/migration-wave-enforce': typeof ApiPublicHooksMigrationWaveEnforceRoute
  '/api/public/hooks/reconcile-pending': typeof ApiPublicHooksReconcilePendingRoute
  '/api/public/hooks/resend-confirmations': typeof ApiPublicHooksResendConfirmationsRoute
  '/api/public/hooks/verify-external-payers': typeof ApiPublicHooksVerifyExternalPayersRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/crypto'
    | '/indicacoes'
    | '/mercado'
    | '/migracao'
    | '/planos'
    | '/presentes'
    | '/primeiros-passos'
    | '/privacidade'
    | '/recuperar'
    | '/renovar-servidor'
    | '/shadow-hub'
    | '/termos'
    | '/tutorial'
    | '/admin'
    | '/dashboard'
    | '/fidelidade'
    | '/play-protect'
    | '/shadow-pass'
    | '/staff-academy'
    | '/staff-chat'
    | '/sugestoes'
    | '/suporte'
    | '/tutoriais'
    | '/pagamento/checkout'
    | '/pagamento/erro'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
    | '/tutorial/$id'
    | '/admin/staff'
    | '/servidor/kraken'
    | '/servidor/status'
    | '/api/chat/license-ai'
    | '/api/public/backend-health'
    | '/api/public/health'
    | '/api/public/tutorials'
    | '/api/apk-builder/'
    | '/api/public/hooks/apk-worker'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/hooks/cleanup-apk-jobs'
    | '/api/public/hooks/crypto-poll'
    | '/api/public/hooks/daily-license-check'
    | '/api/public/hooks/daily-maintenance'
    | '/api/public/hooks/expire-licenses'
    | '/api/public/hooks/migration-wave-enforce'
    | '/api/public/hooks/reconcile-pending'
    | '/api/public/hooks/resend-confirmations'
    | '/api/public/hooks/verify-external-payers'
    | '/api/public/payments/mercadopago'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/crypto'
    | '/indicacoes'
    | '/mercado'
    | '/migracao'
    | '/planos'
    | '/presentes'
    | '/primeiros-passos'
    | '/privacidade'
    | '/recuperar'
    | '/renovar-servidor'
    | '/shadow-hub'
    | '/termos'
    | '/tutorial'
    | '/admin'
    | '/dashboard'
    | '/fidelidade'
    | '/play-protect'
    | '/shadow-pass'
    | '/staff-academy'
    | '/staff-chat'
    | '/sugestoes'
    | '/suporte'
    | '/tutoriais'
    | '/pagamento/checkout'
    | '/pagamento/erro'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
    | '/tutorial/$id'
    | '/admin/staff'
    | '/servidor/kraken'
    | '/servidor/status'
    | '/api/chat/license-ai'
    | '/api/public/backend-health'
    | '/api/public/health'
    | '/api/public/tutorials'
    | '/api/apk-builder'
    | '/api/public/hooks/apk-worker'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/hooks/cleanup-apk-jobs'
    | '/api/public/hooks/crypto-poll'
    | '/api/public/hooks/daily-license-check'
    | '/api/public/hooks/daily-maintenance'
    | '/api/public/hooks/expire-licenses'
    | '/api/public/hooks/migration-wave-enforce'
    | '/api/public/hooks/reconcile-pending'
    | '/api/public/hooks/resend-confirmations'
    | '/api/public/hooks/verify-external-payers'
    | '/api/public/payments/mercadopago'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/crypto'
    | '/indicacoes'
    | '/mercado'
    | '/migracao'
    | '/planos'
    | '/presentes'
    | '/primeiros-passos'
    | '/privacidade'
    | '/recuperar'
    | '/renovar-servidor'
    | '/shadow-hub'
    | '/termos'
    | '/tutorial'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/fidelidade'
    | '/_authenticated/play-protect'
    | '/_authenticated/shadow-pass'
    | '/_authenticated/staff-academy'
    | '/_authenticated/staff-chat'
    | '/_authenticated/sugestoes'
    | '/_authenticated/suporte'
    | '/_authenticated/tutoriais'
    | '/pagamento/checkout'
    | '/pagamento/erro'
    | '/pagamento/pendente'
    | '/pagamento/sucesso'
    | '/tutorial/$id'
    | '/_authenticated/admin/staff'
    | '/_authenticated/servidor/kraken'
    | '/_authenticated/servidor/status'
    | '/api/chat/license-ai'
    | '/api/public/backend-health'
    | '/api/public/health'
    | '/api/public/tutorials'
    | '/api/apk-builder/'
    | '/api/public/hooks/apk-worker'
    | '/api/public/hooks/auto-close-tickets'
    | '/api/public/hooks/cleanup-apk-jobs'
    | '/api/public/hooks/crypto-poll'
    | '/api/public/hooks/daily-license-check'
    | '/api/public/hooks/daily-maintenance'
    | '/api/public/hooks/expire-licenses'
    | '/api/public/hooks/migration-wave-enforce'
    | '/api/public/hooks/reconcile-pending'
    | '/api/public/hooks/resend-confirmations'
    | '/api/public/hooks/verify-external-payers'
    | '/api/public/payments/mercadopago'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  CryptoRoute: typeof CryptoRoute
  IndicacoesRoute: typeof IndicacoesRoute
  MercadoRoute: typeof MercadoRoute
  MigracaoRoute: typeof MigracaoRoute
  PlanosRoute: typeof PlanosRoute
  PresentesRoute: typeof PresentesRoute
  PrimeirosPassosRoute: typeof PrimeirosPassosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarRoute: typeof RecuperarRoute
  RenovarServidorRoute: typeof RenovarServidorRoute
  ShadowHubRoute: typeof ShadowHubRoute
  TermosRoute: typeof TermosRoute
  TutorialRoute: typeof TutorialRouteWithChildren
  PagamentoCheckoutRoute: typeof PagamentoCheckoutRoute
  PagamentoErroRoute: typeof PagamentoErroRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  ApiChatLicenseAiRoute: typeof ApiChatLicenseAiRoute
  ApiPublicBackendHealthRoute: typeof ApiPublicBackendHealthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTutorialsRoute: typeof ApiPublicTutorialsRoute
  ApiApkBuilderIndexRoute: typeof ApiApkBuilderIndexRoute
  ApiPublicHooksApkWorkerRoute: typeof ApiPublicHooksApkWorkerRoute
  ApiPublicHooksAutoCloseTicketsRoute: typeof ApiPublicHooksAutoCloseTicketsRoute
  ApiPublicHooksCleanupApkJobsRoute: typeof ApiPublicHooksCleanupApkJobsRoute
  ApiPublicHooksCryptoPollRoute: typeof ApiPublicHooksCryptoPollRoute
  ApiPublicHooksDailyLicenseCheckRoute: typeof ApiPublicHooksDailyLicenseCheckRoute
  ApiPublicHooksDailyMaintenanceRoute: typeof ApiPublicHooksDailyMaintenanceRoute
  ApiPublicHooksExpireLicensesRoute: typeof ApiPublicHooksExpireLicensesRoute
  ApiPublicHooksMigrationWaveEnforceRoute: typeof ApiPublicHooksMigrationWaveEnforceRoute
  ApiPublicHooksReconcilePendingRoute: typeof ApiPublicHooksReconcilePendingRoute
  ApiPublicHooksResendConfirmationsRoute: typeof ApiPublicHooksResendConfirmationsRoute
  ApiPublicHooksVerifyExternalPayersRoute: typeof ApiPublicHooksVerifyExternalPayersRoute
  ApiPublicPaymentsMercadopagoRoute: typeof ApiPublicPaymentsMercadopagoRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadow-hub': {
      id: '/shadow-hub'
      path: '/shadow-hub'
      fullPath: '/shadow-hub'
      preLoaderRoute: typeof ShadowHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovar-servidor': {
      id: '/renovar-servidor'
      path: '/renovar-servidor'
      fullPath: '/renovar-servidor'
      preLoaderRoute: typeof RenovarServidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiros-passos': {
      id: '/primeiros-passos'
      path: '/primeiros-passos'
      fullPath: '/primeiros-passos'
      preLoaderRoute: typeof PrimeirosPassosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentes': {
      id: '/presentes'
      path: '/presentes'
      fullPath: '/presentes'
      preLoaderRoute: typeof PresentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migracao': {
      id: '/migracao'
      path: '/migracao'
      fullPath: '/migracao'
      preLoaderRoute: typeof MigracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/$id': {
      id: '/tutorial/$id'
      path: '/$id'
      fullPath: '/tutorial/$id'
      preLoaderRoute: typeof TutorialIdRouteImport
      parentRoute: typeof TutorialRoute
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/pendente': {
      id: '/pagamento/pendente'
      path: '/pagamento/pendente'
      fullPath: '/pagamento/pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/erro': {
      id: '/pagamento/erro'
      path: '/pagamento/erro'
      fullPath: '/pagamento/erro'
      preLoaderRoute: typeof PagamentoErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/checkout': {
      id: '/pagamento/checkout'
      path: '/pagamento/checkout'
      fullPath: '/pagamento/checkout'
      preLoaderRoute: typeof PagamentoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutoriais': {
      id: '/_authenticated/tutoriais'
      path: '/tutoriais'
      fullPath: '/tutoriais'
      preLoaderRoute: typeof AuthenticatedTutoriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestoes': {
      id: '/_authenticated/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof AuthenticatedSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-chat': {
      id: '/_authenticated/staff-chat'
      path: '/staff-chat'
      fullPath: '/staff-chat'
      preLoaderRoute: typeof AuthenticatedStaffChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-academy': {
      id: '/_authenticated/staff-academy'
      path: '/staff-academy'
      fullPath: '/staff-academy'
      preLoaderRoute: typeof AuthenticatedStaffAcademyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shadow-pass': {
      id: '/_authenticated/shadow-pass'
      path: '/shadow-pass'
      fullPath: '/shadow-pass'
      preLoaderRoute: typeof AuthenticatedShadowPassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play-protect': {
      id: '/_authenticated/play-protect'
      path: '/play-protect'
      fullPath: '/play-protect'
      preLoaderRoute: typeof AuthenticatedPlayProtectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fidelidade': {
      id: '/_authenticated/fidelidade'
      path: '/fidelidade'
      fullPath: '/fidelidade'
      preLoaderRoute: typeof AuthenticatedFidelidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/apk-builder/': {
      id: '/api/apk-builder/'
      path: '/api/apk-builder'
      fullPath: '/api/apk-builder/'
      preLoaderRoute: typeof ApiApkBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tutorials': {
      id: '/api/public/tutorials'
      path: '/api/public/tutorials'
      fullPath: '/api/public/tutorials'
      preLoaderRoute: typeof ApiPublicTutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backend-health': {
      id: '/api/public/backend-health'
      path: '/api/public/backend-health'
      fullPath: '/api/public/backend-health'
      preLoaderRoute: typeof ApiPublicBackendHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/license-ai': {
      id: '/api/chat/license-ai'
      path: '/api/chat/license-ai'
      fullPath: '/api/chat/license-ai'
      preLoaderRoute: typeof ApiChatLicenseAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servidor/status': {
      id: '/_authenticated/servidor/status'
      path: '/servidor/status'
      fullPath: '/servidor/status'
      preLoaderRoute: typeof AuthenticatedServidorStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidor/kraken': {
      id: '/_authenticated/servidor/kraken'
      path: '/servidor/kraken'
      fullPath: '/servidor/kraken'
      preLoaderRoute: typeof AuthenticatedServidorKrakenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mercadopago': {
      id: '/api/public/payments/mercadopago'
      path: '/api/public/payments/mercadopago'
      fullPath: '/api/public/payments/mercadopago'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-external-payers': {
      id: '/api/public/hooks/verify-external-payers'
      path: '/api/public/hooks/verify-external-payers'
      fullPath: '/api/public/hooks/verify-external-payers'
      preLoaderRoute: typeof ApiPublicHooksVerifyExternalPayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-confirmations': {
      id: '/api/public/hooks/resend-confirmations'
      path: '/api/public/hooks/resend-confirmations'
      fullPath: '/api/public/hooks/resend-confirmations'
      preLoaderRoute: typeof ApiPublicHooksResendConfirmationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-pending': {
      id: '/api/public/hooks/reconcile-pending'
      path: '/api/public/hooks/reconcile-pending'
      fullPath: '/api/public/hooks/reconcile-pending'
      preLoaderRoute: typeof ApiPublicHooksReconcilePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/migration-wave-enforce': {
      id: '/api/public/hooks/migration-wave-enforce'
      path: '/api/public/hooks/migration-wave-enforce'
      fullPath: '/api/public/hooks/migration-wave-enforce'
      preLoaderRoute: typeof ApiPublicHooksMigrationWaveEnforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/expire-licenses': {
      id: '/api/public/hooks/expire-licenses'
      path: '/api/public/hooks/expire-licenses'
      fullPath: '/api/public/hooks/expire-licenses'
      preLoaderRoute: typeof ApiPublicHooksExpireLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-maintenance': {
      id: '/api/public/hooks/daily-maintenance'
      path: '/api/public/hooks/daily-maintenance'
      fullPath: '/api/public/hooks/daily-maintenance'
      preLoaderRoute: typeof ApiPublicHooksDailyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-license-check': {
      id: '/api/public/hooks/daily-license-check'
      path: '/api/public/hooks/daily-license-check'
      fullPath: '/api/public/hooks/daily-license-check'
      preLoaderRoute: typeof ApiPublicHooksDailyLicenseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crypto-poll': {
      id: '/api/public/hooks/crypto-poll'
      path: '/api/public/hooks/crypto-poll'
      fullPath: '/api/public/hooks/crypto-poll'
      preLoaderRoute: typeof ApiPublicHooksCryptoPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-apk-jobs': {
      id: '/api/public/hooks/cleanup-apk-jobs'
      path: '/api/public/hooks/cleanup-apk-jobs'
      fullPath: '/api/public/hooks/cleanup-apk-jobs'
      preLoaderRoute: typeof ApiPublicHooksCleanupApkJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-close-tickets': {
      id: '/api/public/hooks/auto-close-tickets'
      path: '/api/public/hooks/auto-close-tickets'
      fullPath: '/api/public/hooks/auto-close-tickets'
      preLoaderRoute: typeof ApiPublicHooksAutoCloseTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apk-worker': {
      id: '/api/public/hooks/apk-worker'
      path: '/api/public/hooks/apk-worker'
      fullPath: '/api/public/hooks/apk-worker'
      preLoaderRoute: typeof ApiPublicHooksApkWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFidelidadeRoute: typeof AuthenticatedFidelidadeRoute
  AuthenticatedPlayProtectRoute: typeof AuthenticatedPlayProtectRoute
  AuthenticatedShadowPassRoute: typeof AuthenticatedShadowPassRoute
  AuthenticatedStaffAcademyRoute: typeof AuthenticatedStaffAcademyRoute
  AuthenticatedStaffChatRoute: typeof AuthenticatedStaffChatRoute
  AuthenticatedSugestoesRoute: typeof AuthenticatedSugestoesRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedTutoriaisRoute: typeof AuthenticatedTutoriaisRoute
  AuthenticatedServidorKrakenRoute: typeof AuthenticatedServidorKrakenRoute
  AuthenticatedServidorStatusRoute: typeof AuthenticatedServidorStatusRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFidelidadeRoute: AuthenticatedFidelidadeRoute,
  AuthenticatedPlayProtectRoute: AuthenticatedPlayProtectRoute,
  AuthenticatedShadowPassRoute: AuthenticatedShadowPassRoute,
  AuthenticatedStaffAcademyRoute: AuthenticatedStaffAcademyRoute,
  AuthenticatedStaffChatRoute: AuthenticatedStaffChatRoute,
  AuthenticatedSugestoesRoute: AuthenticatedSugestoesRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedTutoriaisRoute: AuthenticatedTutoriaisRoute,
  AuthenticatedServidorKrakenRoute: AuthenticatedServidorKrakenRoute,
  AuthenticatedServidorStatusRoute: AuthenticatedServidorStatusRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TutorialRouteChildren {
  TutorialIdRoute: typeof TutorialIdRoute
}

const TutorialRouteChildren: TutorialRouteChildren = {
  TutorialIdRoute: TutorialIdRoute,
}

const TutorialRouteWithChildren = TutorialRoute._addFileChildren(
  TutorialRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  CryptoRoute: CryptoRoute,
  IndicacoesRoute: IndicacoesRoute,
  MercadoRoute: MercadoRoute,
  MigracaoRoute: MigracaoRoute,
  PlanosRoute: PlanosRoute,
  PresentesRoute: PresentesRoute,
  PrimeirosPassosRoute: PrimeirosPassosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarRoute: RecuperarRoute,
  RenovarServidorRoute: RenovarServidorRoute,
  ShadowHubRoute: ShadowHubRoute,
  TermosRoute: TermosRoute,
  TutorialRoute: TutorialRouteWithChildren,
  PagamentoCheckoutRoute: PagamentoCheckoutRoute,
  PagamentoErroRoute: PagamentoErroRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  ApiChatLicenseAiRoute: ApiChatLicenseAiRoute,
  ApiPublicBackendHealthRoute: ApiPublicBackendHealthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTutorialsRoute: ApiPublicTutorialsRoute,
  ApiApkBuilderIndexRoute: ApiApkBuilderIndexRoute,
  ApiPublicHooksApkWorkerRoute: ApiPublicHooksApkWorkerRoute,
  ApiPublicHooksAutoCloseTicketsRoute: ApiPublicHooksAutoCloseTicketsRoute,
  ApiPublicHooksCleanupApkJobsRoute: ApiPublicHooksCleanupApkJobsRoute,
  ApiPublicHooksCryptoPollRoute: ApiPublicHooksCryptoPollRoute,
  ApiPublicHooksDailyLicenseCheckRoute: ApiPublicHooksDailyLicenseCheckRoute,
  ApiPublicHooksDailyMaintenanceRoute: ApiPublicHooksDailyMaintenanceRoute,
  ApiPublicHooksExpireLicensesRoute: ApiPublicHooksExpireLicensesRoute,
  ApiPublicHooksMigrationWaveEnforceRoute:
    ApiPublicHooksMigrationWaveEnforceRoute,
  ApiPublicHooksReconcilePendingRoute: ApiPublicHooksReconcilePendingRoute,
  ApiPublicHooksResendConfirmationsRoute:
    ApiPublicHooksResendConfirmationsRoute,
  ApiPublicHooksVerifyExternalPayersRoute:
    ApiPublicHooksVerifyExternalPayersRoute,
  ApiPublicPaymentsMercadopagoRoute: ApiPublicPaymentsMercadopagoRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
