// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[SupabaseAuth] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      console.warn('[SupabaseAuth] Unauthorized: request headers unavailable');
      throw new Error('Unauthorized');
    }

    const authHeader = request.headers.get('authorization');
    if (!authHeader) {
      // Never log request headers here: they may contain cookies or credentials.
      console.warn('[SupabaseAuth] Unauthorized: authorization header missing', {
        path: request.url ? new URL(request.url).pathname : undefined,
        method: request.method,
      });
      throw new Error('Unauthorized');
    }

    const bearerMatch = /^Bearer\s+(.+)$/i.exec(authHeader);
    if (!bearerMatch) {
      console.warn('[SupabaseAuth] Unauthorized: unsupported authorization scheme');
      throw new Error('Unauthorized');
    }

    const token = bearerMatch[1].trim();
    if (!token || token.split('.').length !== 3) {
      console.warn('[SupabaseAuth] Unauthorized: malformed bearer token');
      throw new Error('Unauthorized');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      // Avoid logging provider error details or any token-derived material.
      console.warn('[SupabaseAuth] Unauthorized: token validation failed');
      throw new Error('Unauthorized');
    }

    if (!data.claims.sub) {
      console.warn('[SupabaseAuth] Unauthorized: token subject missing');
      throw new Error('Unauthorized');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
